# -*- mode: python ; coding: utf-8 -*-

import os
import sys

# 获取当前目录
current_dir = os.getcwd()

a = Analysis(
    ['backend/api.py'],
    pathex=[current_dir],
    binaries=[],
    datas=[
        ('prompts', 'prompts'),
        ('js', 'js'),
        ('css', 'css'),
        ('index.html', '.'),
        ('lazynoodle.png', '.'),
        #('worlds', 'worlds'),
        ('.env.example', '.'),
        ('backend', 'backend'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.loops.asyncio',
        'uvicorn.loops.uvloop',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.http.httptools_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.protocols.websockets.websockets_impl',
        'uvicorn.logging',
        'uvicorn.middleware',
        'uvicorn.middleware.proxy_headers',
        'uvicorn.middleware.message_logger',
        'uvicorn.config',
        'uvicorn.server',
        'fastapi',
        'fastapi.routing',
        'fastapi.applications',
        'openai',
        'dotenv',
        'dotenv.main',
        'dotenv.parser',
        'requests',
        'httpx',
        'pydantic',
        'pydantic_core',
        'starlette',
        'starlette.routing',
        'starlette.applications',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.middleware.errors',
        'starlette.middleware.exceptions',
        'starlette.middleware.base',
        'starlette.responses',
        'starlette.requests',
        'starlette.background',
        'starlette.concurrency',
        'starlette.types',
        'starlette.websockets',
        'starlette.datastructures',
        'starlette.exceptions',
        'starlette.templating',
        'starlette.staticfiles',
        'anyio',
        'anyio.from_thread',
        'anyio.to_thread',
        'anyio.abc',
        'anyio.streams',
        'httpcore',
        'httpcore._api',
        'httpcore._async',
        'httpcore._sync',
        'h11',
        'h11._connection',
        'h11._events',
        'h11._headers',
        'h11._readers',
        'h11._util',
        'h11._writers',
        'asyncio',
        'concurrent',
        'concurrent.futures',
        'concurrent.futures.thread',
        'threading',
        'typing',
        'typing_extensions',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        'PyQt5', 'PyQt6', 'PySide2', 'PySide6',
        'matplotlib', 'tkinter', 'IPython', 'jupyter',
        'PIL', 'pillow', 'numpy', 'pandas',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    name='LazyNoodle',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    runtime_tmpdir=None,
    console=True,
)